# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["KP_InternalSystem.csproj", "./"]
RUN dotnet restore "KP_InternalSystem.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "KP_InternalSystem.csproj" -c Release -o /app/build

# Stage 2: Publish
FROM build AS publish
RUN dotnet publish "KP_InternalSystem.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Stage 3: Final Run
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KP_InternalSystem.dll"]