// <auto-generated />
using System;
using KP_InternalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KP_InternalSystem.Migrations
{
    [DbContext(typeof(RatDbContext))]
    [Migration("20260129072454_ReinitProductMaster")]
    partial class ReinitProductMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KP_InternalSystem.Models.DailyProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DirtyCoal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Lignite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Melawan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pelikan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pinang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PinangHCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PinangHGHS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PinangHGLS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PinangLGHS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PinangLGLS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("DailyProductions");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_department");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department_name");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("id_division");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DivisionId");

                    b.ToTable("department", "dbo");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_division");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("division_name");

                    b.HasKey("DivisionId");

                    b.ToTable("division", "dbo");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_location");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_name");

                    b.HasKey("LocationId");

                    b.ToTable("location", "dbo");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Pit", b =>
                {
                    b.Property<int>("PitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pit");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PitId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("id_department");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("e_date");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("id_location");

                    b.Property<string>("PitCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pit_code");

                    b.Property<string>("PitNameOfficial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pit_name_official");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("PitId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocationId");

                    b.ToTable("pit_official");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.PitAlias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alias");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AliasId"));

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alias_name");

                    b.Property<int>("PitId")
                        .HasColumnType("int")
                        .HasColumnName("id_pit");

                    b.HasKey("AliasId");

                    b.HasIndex("PitId");

                    b.ToTable("pit_alias", "dbo");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("id_division");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.HasKey("ProductId");

                    b.HasIndex("DivisionId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.ProductAlias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alias");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AliasId"));

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alias_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.HasKey("AliasId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_alias");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.UserActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("UserActivityLog");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Department", b =>
                {
                    b.HasOne("KP_InternalSystem.Models.Division", "Division")
                        .WithMany("Departments")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Pit", b =>
                {
                    b.HasOne("KP_InternalSystem.Models.Department", "Department")
                        .WithMany("Pits")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KP_InternalSystem.Models.Location", "Location")
                        .WithMany("Pits")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.PitAlias", b =>
                {
                    b.HasOne("KP_InternalSystem.Models.Pit", "Pit")
                        .WithMany("PitAliases")
                        .HasForeignKey("PitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pit");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Product", b =>
                {
                    b.HasOne("KP_InternalSystem.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.ProductAlias", b =>
                {
                    b.HasOne("KP_InternalSystem.Models.Product", "Product")
                        .WithMany("ProductAliases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Department", b =>
                {
                    b.Navigation("Pits");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Division", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Location", b =>
                {
                    b.Navigation("Pits");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Pit", b =>
                {
                    b.Navigation("PitAliases");
                });

            modelBuilder.Entity("KP_InternalSystem.Models.Product", b =>
                {
                    b.Navigation("ProductAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
